# Generated by Django 4.1 on 2022-12-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
