# Generated by Django 4.1 on 2022-11-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Infractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('celular', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalles', models.CharField(max_length=50)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultaApp.multa')),
            ],
        ),
    ]
