# Generated by Django 4.1 on 2022-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultaApp', '0002_alter_multa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infractor',
            name='detalles',
            field=models.CharField(max_length=300),
        ),
    ]
