# Generated by Django 4.1 on 2022-11-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultaApp', '0003_alter_infractor_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infractor',
            name='multa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MultaApp.multa'),
        ),
    ]
