# Generated by Django 4.1 on 2022-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultaApp', '0004_alter_infractor_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='infractor',
            name='monto',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
