# Generated by Django 4.1 on 2022-12-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluacionFinalApp', '0006_remove_producto_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='hora',
            field=models.TimeField(),
        ),
    ]
